# Generated by Django 5.0.1 on 2024-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='expery',
            field=models.DateTimeField(null=True),
        ),
    ]
