# Generated by Django 5.0.1 on 2024-02-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_course_studentprofile_approval_status_and_more'),
        ('teacher', '0003_exam_expery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titile', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Banner_image', models.FileField(upload_to='Bannerimage')),
                ('Metirial', models.FileField(upload_to='Meterials')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Videostudylink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titile', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='Meterials')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.teacherprofile')),
            ],
        ),
    ]
