# Generated by Django 5.0.1 on 2024-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_joblist_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='job_category',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('IT', 'IT'), ('Technical', 'Technical'), ('Accounts', 'Accounts'), ('Mamagement', 'Management'), ('HR', 'HR'), ('Marketing', 'Marketing'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
