# Generated by Django 5.0.1 on 2024-02-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_education_experiance_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='Photo',
            field=models.FileField(blank=True, upload_to='student_photo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='Student_resumes'),
        ),
    ]
