# Generated by Django 5.0.1 on 2024-02-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_studentprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeWritingTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_title', models.CharField(max_length=255)),
                ('tip', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
